### ISSUE TITLE
[NETWORK] Netty Channel Resetting FML Network?

### ISSUE THREAD

**Issue by Hexeption** [magmafoundation/Magma-1.16.x#74]
When connecting using a Forge Client the server is not sending the correct channel attribute to the client making the client think it's a vanilla server.

` Connected to a vanilla server. Catching up missing behaviour.`

This breaks mods a lot of mods like ie mekanism.

``` java
   public static void handleClientLoginSuccess(NetworkManager manager) {
        if (isVanillaConnection(manager)) {
            LOGGER.info("Connected to a vanilla server. Catching up missing behaviour.");
            ConfigTracker.INSTANCE.loadDefaultServerConfigs();
        } else {
            LOGGER.info("Connected to a modded server.");
        }
    }
```

`isVanillaConnection` is returning true when it should be returning false and not loading default server configs.

**Comment by pacas00** [comment]
Comparing the Forge 1.16 patches to the patches here, I'm pretty sure that the `LoginHandler().fireEvents()` in ServerLoginNetHandler should be setting `ServerLoginNetHandler.this.currentLoginState = State.NEGOTIATING;` instead of `READY_TO_ACCEPT`.

Reference Forge: Line 41 https://github.com/MinecraftForge/MinecraftForge/blob/1.16.x/patches/minecraft/net/minecraft/network/login/ServerLoginNetHandler.java.patch
Magma: Line 254 https://github.com/magmafoundation/Magma-1.16.x/blob/1.16.x/patches/minecraft/net/minecraft/network/login/ServerLoginNetHandler.java.patch
(Originally called from Line 179 in this patchfile's case)

Unfortunately, I havent had enough time to dig further into this, and don't understand it enough to really help much.
Changing that to NEGOTIATING does cause an out of bounds error though.
